### ISSUE TITLE
Keep child repo history when pushing

### ISSUE THREAD

**Issue by minimaluminium** [NxtLvLSoftware/git-subtree-action#6]
👋 Would it be possible to keep the history of the child repo when using this action? I tried it without the `force` argument thinking it'd do normal push instead of replacing the history, but got an error `error: failed to push some refs to ''`.

My config is:

```yml
- uses: nxtlvlsoftware/git-subtree-action@1.1
  with:
    repo: 'owner/repo'
    path: 'packages/name'
    deploy_key: ${{secrets.GITHUB_DEPLOY_KEY}}
    branch: main
```
